# all options https://taplo.tamasfe.dev/configuration/formatter-options.html

# This is a taplo configuration file.
# For more information, see: https://taplo.tamasfe.dev/configuration/
exclude = ["**/target/**"]
include = ["**/*.toml"]

[formatting]
array_auto_collapse = false
array_auto_expand = true
indent_string = "	"         # tab
inline_table_expand = false
reorder_arrays = true
reorder_keys = true

[[rule]]
include = ["Cargo.toml"]
keys = ["workspace.dependencies"]

[rule.formatting]
reorder_keys = true
