//! Verifier logic for the Wormhole circuit.
//!
//! This module provides the [`WormholeVerifier`] type, which allows for the verification of
//! zero-knowledge proofs generated by the Wormhole circuit.
//!
//! The typical usage flow involves:
//! 1. Initializing the verifier from pre-built circuit data via [`WormholeVerifier::new_from_bytes()`].
//! 2. Deserializing a [`ProofWithPublicInputs`].
//! 3. Verifying the proof using [`WormholeVerifier::verify`].
//!
//! # Example
//!
//! ```ignore
//! use qp_wormhole_verifier::{WormholeVerifier, ProofWithPublicInputs, C, D, F};
//!
//! // Load verifier from pre-serialized bytes
//! let verifier = WormholeVerifier::new_from_bytes(verifier_bytes, common_bytes)?;
//!
//! // Deserialize the proof
//! let proof = ProofWithPublicInputs::<F, C, D>::from_bytes(proof_bytes, &verifier.circuit_data.common)?;
//!
//! // Verify
//! verifier.verify(proof)?;
//! ```
#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(not(feature = "std"))]
extern crate alloc;

#[cfg(not(feature = "std"))]
use alloc::vec::Vec;
#[cfg(feature = "std")]
use std::vec::Vec;

use anyhow::anyhow;
use sha2::{Digest, Sha256};
#[cfg(feature = "std")]
use std::path::Path;

// Re-export types from qp-plonky2-verifier
pub use qp_plonky2_verifier::{
    CommonCircuitData, ProofWithPublicInputs, VerifierCircuitData, VerifierOnlyCircuitData, C, D, F,
};

use qp_plonky2_verifier::field::types::PrimeField64;
use qp_plonky2_verifier::util::serialization::DefaultGateSerializer;

// Re-export input types from qp-wormhole-inputs
pub use qp_wormhole_inputs::{
    AggregatedPublicCircuitInputs, BlockData, BytesDigest, PublicCircuitInputs,
    PublicInputsByAccount,
};

/// Parse public inputs from a proof.
pub fn parse_public_inputs(
    proof: &ProofWithPublicInputs<F, C, D>,
) -> anyhow::Result<PublicCircuitInputs> {
    let u64s: Vec<u64> = proof
        .public_inputs
        .iter()
        .map(|f| f.to_canonical_u64())
        .collect();
    PublicCircuitInputs::try_from_u64_slice(&u64s)
}

/// Parse aggregated public inputs from a proof.
pub fn parse_aggregated_public_inputs(
    proof: &ProofWithPublicInputs<F, C, D>,
) -> anyhow::Result<AggregatedPublicCircuitInputs> {
    let u64s: Vec<u64> = proof
        .public_inputs
        .iter()
        .map(|f| f.to_canonical_u64())
        .collect();
    AggregatedPublicCircuitInputs::try_from_u64_slice(&u64s)
}

/// Verifier for Wormhole circuit proofs.
///
/// This struct wraps the circuit verification data and provides methods to verify proofs.
#[derive(Debug)]
pub struct WormholeVerifier {
    pub circuit_data: VerifierCircuitData<F, C, D>,
}

/// Stable identity pins for a verifier/common artifact pair.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct VerifierCircuitIdentity {
    pub verifier_sha256: [u8; 32],
    pub common_sha256: [u8; 32],
}

impl VerifierCircuitIdentity {
    pub fn from_bytes(verifier_bytes: &[u8], common_bytes: &[u8]) -> Self {
        Self {
            verifier_sha256: Sha256::digest(verifier_bytes).into(),
            common_sha256: Sha256::digest(common_bytes).into(),
        }
    }

    pub fn from_circuit_data(circuit_data: &VerifierCircuitData<F, C, D>) -> anyhow::Result<Self> {
        let common_bytes = circuit_data
            .common
            .to_bytes(&DefaultGateSerializer)
            .map_err(|e| anyhow!("failed to serialize common circuit data: {}", e))?;
        let verifier_bytes = circuit_data
            .verifier_only
            .to_bytes()
            .map_err(|e| anyhow!("failed to serialize verifier-only circuit data: {}", e))?;
        Ok(Self::from_bytes(&verifier_bytes, &common_bytes))
    }
}

impl WormholeVerifier {
    /// Creates a new [`WormholeVerifier`] from verifier and common data bytes.
    ///
    /// This is a low-level trusting constructor. Prefer
    /// [`WormholeVerifier::new_from_bytes_checked`] when you have an expected verifier/common
    /// identity to pin against.
    pub fn new_from_bytes(
        verifier_bytes: &[u8],
        common_bytes: &[u8],
    ) -> Result<Self, &'static str> {
        let verifier_only = VerifierOnlyCircuitData::from_bytes(verifier_bytes.to_vec())
            .map_err(|_| "Failed to deserialize verifier data from bytes")?;

        let common = CommonCircuitData::from_bytes(common_bytes.to_vec(), &DefaultGateSerializer)
            .map_err(|_| "Failed to deserialize common circuit data from bytes")?;

        let circuit_data = VerifierCircuitData {
            verifier_only,
            common,
        };

        Ok(Self { circuit_data })
    }

    /// Creates a new verifier and rejects artifact bytes that do not match the expected identity.
    pub fn new_from_bytes_checked(
        verifier_bytes: &[u8],
        common_bytes: &[u8],
        expected_identity: &VerifierCircuitIdentity,
    ) -> anyhow::Result<Self> {
        let actual_identity = VerifierCircuitIdentity::from_bytes(verifier_bytes, common_bytes);
        if &actual_identity != expected_identity {
            return Err(anyhow!("verifier/common artifact identity mismatch"));
        }

        Self::new_from_bytes(verifier_bytes, common_bytes).map_err(|e| anyhow!("{}", e))
    }

    /// Creates a new [`WormholeVerifier`] from a verifier and common data files.
    ///
    /// This is a low-level trusting constructor. Prefer
    /// [`WormholeVerifier::new_from_files_checked`] when loading production artifacts from disk.
    #[cfg(feature = "std")]
    pub fn new_from_files(
        verifier_data_path: &Path,
        common_data_path: &Path,
    ) -> anyhow::Result<Self> {
        let verifier_bytes = std::fs::read(verifier_data_path)?;

        let verifier_only = VerifierOnlyCircuitData::from_bytes(verifier_bytes).map_err(|e| {
            anyhow!(
                "Failed to deserialize verifier data from {:?}: {}",
                verifier_data_path,
                e
            )
        })?;

        let common_bytes = std::fs::read(common_data_path)?;
        let common =
            CommonCircuitData::from_bytes(common_bytes, &DefaultGateSerializer).map_err(|e| {
                anyhow!(
                    "Failed to deserialize common circuit data from {:?}: {}",
                    common_data_path,
                    e
                )
            })?;

        let circuit_data = VerifierCircuitData {
            verifier_only,
            common,
        };

        Ok(Self { circuit_data })
    }

    /// Creates a new verifier from files and rejects artifacts whose identity does not match the
    /// expected pinned verifier/common bytes.
    #[cfg(feature = "std")]
    pub fn new_from_files_checked(
        verifier_data_path: &Path,
        common_data_path: &Path,
        expected_identity: &VerifierCircuitIdentity,
    ) -> anyhow::Result<Self> {
        let verifier_bytes = std::fs::read(verifier_data_path)?;
        let common_bytes = std::fs::read(common_data_path)?;
        Self::new_from_bytes_checked(&verifier_bytes, &common_bytes, expected_identity)
    }

    pub fn identity(&self) -> anyhow::Result<VerifierCircuitIdentity> {
        VerifierCircuitIdentity::from_circuit_data(&self.circuit_data)
    }

    /// Verify a [`ProofWithPublicInputs`].
    ///
    /// # Errors
    ///
    /// Returns an error if the proof is not valid.
    pub fn verify_ref(&self, proof: &ProofWithPublicInputs<F, C, D>) -> anyhow::Result<()> {
        self.circuit_data
            .verify(proof.clone())
            .map_err(|e| anyhow!("proof verification failed: {}", e))
    }

    /// Verify a [`ProofWithPublicInputs`].
    ///
    /// # Errors
    ///
    /// Returns an error if the proof is not valid.
    pub fn verify(&self, proof: ProofWithPublicInputs<F, C, D>) -> anyhow::Result<()> {
        self.verify_ref(&proof)
    }
}
