[package]
authors.workspace = true
description = "Plonky2 circuit proving knowledge of a wormhole-address secret"
edition.workspace = true
license.workspace = true
name = "qp-ownership-circuit"
readme = "README.md"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
qp-ownership-inputs = { version = "=4.3.0", path = "../inputs", default-features = false }
qp-plonky2 = { workspace = true }
wormhole-circuit = { package = "qp-wormhole-circuit", version = "=4.3.0", path = "../../wormhole/circuit", default-features = false }
zk-circuits-common = { package = "qp-zk-circuits-common", version = "=4.3.0", path = "../../common", default-features = false }

[features]
default = ["std"]
std = [
	"anyhow/std",
	"qp-ownership-inputs/std",
	"qp-plonky2/std",
	"wormhole-circuit/std",
	"zk-circuits-common/std",
]

[lints]
workspace = true
