use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};
use std::fs::write;
use std::path::Path;

/// SHA256 hashes of the circuit binary/files.
/// Used to detect mismatches between different copies of the artifacts.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
pub struct BinaryHashes {
    // ---- Leaf artifacts ----
    #[serde(skip_serializing_if = "Option::is_none")]
    pub common: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verifier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prover: Option<String>,

    // ---- Layer-0 artifacts ----
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregated_common: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregated_verifier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregated_prover: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub dummy_proof: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layer0_targets: Option<String>,

    // ---- Layer-1 artifacts ----
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layer1_common: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layer1_verifier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layer1_prover: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layer1_targets: Option<String>,
}

/// Canonical artifact binary filenames generated by our wormhole circuit builder
#[allow(clippy::type_complexity)]
const ARTIFACTS: &[(
    &str,
    fn(&BinaryHashes) -> &Option<String>,
    fn(&mut BinaryHashes, Option<String>),
)] = &[
    // Leaf
    ("common.bin", |h| &h.common, |h, v| h.common = v),
    ("verifier.bin", |h| &h.verifier, |h, v| h.verifier = v),
    ("prover.bin", |h| &h.prover, |h, v| h.prover = v),
    // Layer-0
    (
        "aggregated_common.bin",
        |h| &h.aggregated_common,
        |h, v| h.aggregated_common = v,
    ),
    (
        "aggregated_verifier.bin",
        |h| &h.aggregated_verifier,
        |h, v| h.aggregated_verifier = v,
    ),
    (
        "aggregated_prover.bin",
        |h| &h.aggregated_prover,
        |h, v| h.aggregated_prover = v,
    ),
    (
        "dummy_proof.bin",
        |h| &h.dummy_proof,
        |h, v| h.dummy_proof = v,
    ),
    (
        "layer0_targets.json",
        |h| &h.layer0_targets,
        |h, v| h.layer0_targets = v,
    ),
    // Layer-1
    (
        "layer1_common.bin",
        |h| &h.layer1_common,
        |h, v| h.layer1_common = v,
    ),
    (
        "layer1_verifier.bin",
        |h| &h.layer1_verifier,
        |h, v| h.layer1_verifier = v,
    ),
    (
        "layer1_prover.bin",
        |h| &h.layer1_prover,
        |h, v| h.layer1_prover = v,
    ),
    (
        "layer1_targets.json",
        |h| &h.layer1_targets,
        |h, v| h.layer1_targets = v,
    ),
];

impl BinaryHashes {
    /// Compute SHA256 hash of a file and return as hex string.
    pub fn hash_file<P: AsRef<Path>>(path: P) -> Result<String> {
        use sha2::{Digest, Sha256};

        let path_ref = path.as_ref();
        let bytes = std::fs::read(path_ref)
            .map_err(|e| anyhow!("Failed to read {}: {}", path_ref.display(), e))?;
        let hash = Sha256::digest(&bytes);
        Ok(hex::encode(hash))
    }

    /// Compute hashes for all known artifact files in a directory.
    ///
    /// Missing files are represented as `None` so config remains compatible across
    /// flows that generate only a subset of artifacts.
    pub fn from_directory<P: AsRef<Path>>(bins_dir: P) -> Result<Self> {
        let dir = bins_dir.as_ref();
        let mut out = Self::default();

        for (filename, _get, set) in ARTIFACTS {
            let h = Self::hash_file(dir.join(filename)).ok();
            set(&mut out, h);
        }

        Ok(out)
    }
}

/// Configuration stored alongside circuit binaries (config.json).
/// This struct is used by both circuit-builder (to save config) and
/// aggregator (to load config when aggregating proofs).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircuitBinsConfig {
    pub num_leaf_proofs: usize,
    pub num_layer0_proofs: Option<usize>,

    /// SHA256 hashes of the artifact files for integrity verification.
    /// Optional for backward compatibility with older configs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hashes: Option<BinaryHashes>,
}

impl CircuitBinsConfig {
    /// Create a new config from the bins directory with the circuit artifacts
    pub fn new<P: AsRef<Path>>(bins_dir: P) -> Result<Self> {
        // We first extract the circuit width of each layer (number of leaf proofs and number of layer0 proofs
        // from the serialized target files
        let (num_leaf_proofs, num_layer0_proofs) = get_aggr_widths(&bins_dir)?;
        let hashes = Some(BinaryHashes::from_directory(bins_dir)?);
        Ok(Self {
            num_leaf_proofs,
            num_layer0_proofs,
            hashes,
        })
    }

    /// Add hashes computed from the artifact files in a directory
    pub fn with_hashes_from_directory<P: AsRef<Path>>(mut self, bins_dir: P) -> Result<Self> {
        self.hashes = Some(BinaryHashes::from_directory(bins_dir)?);
        Ok(self)
    }

    /// Load config from a directory containing circuit binaries
    pub fn load<P: AsRef<Path>>(bins_dir: P) -> Result<Self> {
        let config_path = bins_dir.as_ref().join("config.json");
        let config_str = std::fs::read_to_string(&config_path)
            .map_err(|e| anyhow!("Failed to read {}: {}", config_path.display(), e))?;
        serde_json::from_str(&config_str)
            .map_err(|e| anyhow!("Failed to parse {}: {}", config_path.display(), e))
    }

    /// Save config to a directory
    pub fn save<P: AsRef<Path>>(&self, bins_dir: P) -> Result<()> {
        let config_path = bins_dir.as_ref().join("config.json");
        let config_str = serde_json::to_string_pretty(self)
            .map_err(|e| anyhow!("Failed to serialize config: {}", e))?;
        write(&config_path, config_str)
            .map_err(|e| anyhow!("Failed to write {}: {}", config_path.display(), e))?;
        println!("Config saved to {}", config_path.display());
        Ok(())
    }

    /// Verify that the artifact files in a directory match the stored hashes.
    ///
    /// Returns Ok(()) if all present hashes match.
    /// Returns Err if any hash mismatches or if config has hashes but a file is missing.
    /// If no hashes are stored in config, verification is skipped.
    pub fn verify_hashes<P: AsRef<Path>>(&self, bins_dir: P) -> Result<()> {
        let Some(ref stored_hashes) = self.hashes else {
            return Ok(());
        };

        let dir = bins_dir.as_ref();
        let current_hashes = BinaryHashes::from_directory(dir)?;

        let mut mismatches = Vec::new();

        for (filename, get, _set) in ARTIFACTS {
            let stored = get(stored_hashes);
            let current = get(&current_hashes);

            match (stored, current) {
                (Some(s), Some(c)) if s != c => {
                    mismatches.push(format!(
                        "{}: expected {}..., got {}...",
                        filename,
                        &s[..s.len().min(16)],
                        &c[..c.len().min(16)]
                    ));
                }
                (Some(_), None) => {
                    mismatches.push(format!(
                        "{}: hash in config but file not found or unreadable",
                        filename
                    ));
                }
                _ => {}
            }
        }

        if mismatches.is_empty() {
            Ok(())
        } else {
            Err(anyhow!(
                "Binary hash verification failed:\n  {}\n\n\
                 This can happen if artifacts were regenerated without updating config.json.\n\
                 Run the circuit builder to regenerate all artifacts and config.",
                mismatches.join("\n  ")
            ))
        }
    }
}

/// Try to read the serialized target layout files from
/// from each layer to gather the widths of each
fn get_aggr_widths<P: AsRef<Path>>(bins_dir: P) -> Result<(usize, Option<usize>)> {
    let dir = bins_dir.as_ref();
    // This is an essential artifact, so we throw error if missing.
    let layer0_targets_path = dir.join("layer0_targets.json");
    let layer0_targets_bytes = std::fs::read(&layer0_targets_path)
        .map_err(|e| anyhow!("Failed to read {}: {}", layer0_targets_path.display(), e))?;
    let layer0_targets: crate::layer0::prover::targets_layout::Layer0TargetsLayoutD =
        serde_json::from_slice(&layer0_targets_bytes)
            .map_err(|e| anyhow!("Failed to parse {}: {}", layer0_targets_path.display(), e))?;

    let num_leaf_proofs = layer0_targets.n_leaf;

    // If there is no layer1_targets.json, we just return after setting num_leaf_proofs
    let layer1_targets_path = dir.join("layer1_targets.json");
    let layer1_targets_bytes = std::fs::read(&layer1_targets_path)
        .map_err(|e| anyhow!("Failed to read {}: {}", layer1_targets_path.display(), e));

    // If it failed to load then we assume the config doesn't conatain layer 1 artifacts so
    // we assign a None to `num_layer0_proofs`.
    if layer1_targets_bytes.is_err() {
        return Ok((num_leaf_proofs, None));
    }
    // Otherwise we try to parse it and then set the `num_layer0_proofs`
    let layer1_targets: crate::layer1::prover::targets_layout::Layer1TargetsLayoutD =
        serde_json::from_slice(&layer1_targets_bytes.unwrap())
            .map_err(|e| anyhow!("Failed to parse {}: {}", layer1_targets_path.display(), e))?;

    Ok((num_leaf_proofs, Some(layer1_targets.n_layer0)))
}
