use anyhow::{anyhow, Result};
use serde::{Deserialize, Serialize};
use std::fs::write;
use std::path::Path;

/// SHA256 hashes of the circuit binary/files.
/// Used to detect mismatches between different copies of the artifacts.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq, Eq)]
pub struct BinaryHashes {
    // ---- Leaf artifacts ----
    #[serde(skip_serializing_if = "Option::is_none")]
    pub common: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verifier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub prover: Option<String>,

    // ---- Layer-0 artifacts ----
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregated_common: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregated_verifier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub aggregated_prover: Option<String>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub dummy_proof: Option<String>,

    // ---- Layer-1 artifacts ----
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layer1_common: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layer1_verifier: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub layer1_prover: Option<String>,
}

/// Canonical artifact binary filenames generated by our wormhole circuit builder
#[allow(clippy::type_complexity)]
const ARTIFACTS: &[(
    &str,
    fn(&BinaryHashes) -> &Option<String>,
    fn(&mut BinaryHashes, Option<String>),
)] = &[
    // Leaf
    ("common.bin", |h| &h.common, |h, v| h.common = v),
    ("verifier.bin", |h| &h.verifier, |h, v| h.verifier = v),
    ("prover.bin", |h| &h.prover, |h, v| h.prover = v),
    // Layer-0
    (
        "aggregated_common.bin",
        |h| &h.aggregated_common,
        |h, v| h.aggregated_common = v,
    ),
    (
        "aggregated_verifier.bin",
        |h| &h.aggregated_verifier,
        |h, v| h.aggregated_verifier = v,
    ),
    (
        "aggregated_prover.bin",
        |h| &h.aggregated_prover,
        |h, v| h.aggregated_prover = v,
    ),
    (
        "dummy_proof.bin",
        |h| &h.dummy_proof,
        |h, v| h.dummy_proof = v,
    ),
    // Layer-1
    (
        "layer1_common.bin",
        |h| &h.layer1_common,
        |h, v| h.layer1_common = v,
    ),
    (
        "layer1_verifier.bin",
        |h| &h.layer1_verifier,
        |h, v| h.layer1_verifier = v,
    ),
    (
        "layer1_prover.bin",
        |h| &h.layer1_prover,
        |h, v| h.layer1_prover = v,
    ),
];

impl BinaryHashes {
    /// Compute SHA256 hash of a file and return as hex string.
    pub fn hash_file<P: AsRef<Path>>(path: P) -> Result<String> {
        use sha2::{Digest, Sha256};

        let path_ref = path.as_ref();
        let bytes = std::fs::read(path_ref)
            .map_err(|e| anyhow!("Failed to read {}: {}", path_ref.display(), e))?;
        let hash = Sha256::digest(&bytes);
        Ok(hex::encode(hash))
    }

    /// Compute hashes for all known artifact files in a directory.
    ///
    /// Missing files are represented as `None` so config remains compatible across
    /// flows that generate only a subset of artifacts.
    pub fn from_directory<P: AsRef<Path>>(bins_dir: P) -> Result<Self> {
        let dir = bins_dir.as_ref();
        let mut out = Self::default();

        for (filename, _get, set) in ARTIFACTS {
            let h = Self::hash_file(dir.join(filename)).ok();
            set(&mut out, h);
        }

        Ok(out)
    }
}

/// Configuration stored alongside circuit binaries (config.json).
/// This struct is used by both circuit-builder (to save config) and
/// aggregator (to load config when aggregating proofs).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CircuitBinsConfig {
    pub num_leaf_proofs: usize,
    pub num_layer0_proofs: Option<usize>,

    /// SHA256 hashes of the artifact files for integrity verification.
    /// Optional for backward compatibility with older configs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hashes: Option<BinaryHashes>,
}

impl CircuitBinsConfig {
    /// Create a new config from the bins directory with the circuit artifacts
    pub fn new<P: AsRef<Path>>(
        bins_dir: P,
        num_leaf_proofs: usize,
        num_layer0_proofs: Option<usize>,
    ) -> Result<Self> {
        // We first extract the circuit width of each layer (number of leaf proofs and number of layer0 proofs
        // from the serialized target files
        let hashes = Some(BinaryHashes::from_directory(bins_dir)?);
        Ok(Self {
            num_leaf_proofs,
            num_layer0_proofs,
            hashes,
        })
    }

    /// Load config from a directory containing circuit binaries
    pub fn load<P: AsRef<Path>>(bins_dir: P) -> Result<Self> {
        let config_path = bins_dir.as_ref().join("config.json");
        let config_str = std::fs::read_to_string(&config_path)
            .map_err(|e| anyhow!("Failed to read {}: {}", config_path.display(), e))?;
        serde_json::from_str(&config_str)
            .map_err(|e| anyhow!("Failed to parse {}: {}", config_path.display(), e))
    }

    /// Save config to a directory
    pub fn save<P: AsRef<Path>>(&self, bins_dir: P) -> Result<()> {
        let config_path = bins_dir.as_ref().join("config.json");
        let config_str = serde_json::to_string_pretty(self)
            .map_err(|e| anyhow!("Failed to serialize config: {}", e))?;
        write(&config_path, config_str)
            .map_err(|e| anyhow!("Failed to write {}: {}", config_path.display(), e))?;
        println!("Config saved to {}", config_path.display());
        Ok(())
    }

    /// Ensure the config includes hashes for every artifact produced by the safe builder flow.
    pub fn ensure_generated_artifact_hashes_present(&self, include_prover: bool) -> Result<()> {
        let Some(ref hashes) = self.hashes else {
            return Err(anyhow!(
                "config is missing integrity hashes for generated artifacts"
            ));
        };

        let mut missing = Vec::new();

        if hashes.common.is_none() {
            missing.push("common.bin");
        }
        if hashes.verifier.is_none() {
            missing.push("verifier.bin");
        }
        if hashes.dummy_proof.is_none() {
            missing.push("dummy_proof.bin");
        }
        if hashes.aggregated_common.is_none() {
            missing.push("aggregated_common.bin");
        }
        if hashes.aggregated_verifier.is_none() {
            missing.push("aggregated_verifier.bin");
        }

        if include_prover {
            if hashes.prover.is_none() {
                missing.push("prover.bin");
            }
            if hashes.aggregated_prover.is_none() {
                missing.push("aggregated_prover.bin");
            }
        }

        if self.num_layer0_proofs.is_some() {
            if hashes.layer1_common.is_none() {
                missing.push("layer1_common.bin");
            }
            if hashes.layer1_verifier.is_none() {
                missing.push("layer1_verifier.bin");
            }
            if include_prover && hashes.layer1_prover.is_none() {
                missing.push("layer1_prover.bin");
            }
        }

        if missing.is_empty() {
            Ok(())
        } else {
            Err(anyhow!(
                "config is missing integrity hashes for generated artifacts: {}",
                missing.join(", ")
            ))
        }
    }

    /// Verify that the artifact files in a directory match the stored hashes.
    ///
    /// Returns Ok(()) if all present hashes match.
    /// Returns Err if any hash mismatches or if config has hashes but a file is missing.
    /// Missing metadata is rejected by default. Use
    /// [`CircuitBinsConfig::verify_hashes_allow_missing_metadata`] only for explicit legacy
    /// compatibility flows.
    pub fn verify_hashes<P: AsRef<Path>>(&self, bins_dir: P) -> Result<()> {
        self.verify_hashes_inner(bins_dir, true)
    }

    /// Legacy escape hatch that verifies any hashes that are present but does not fail closed when
    /// metadata is missing.
    pub fn verify_hashes_allow_missing_metadata<P: AsRef<Path>>(&self, bins_dir: P) -> Result<()> {
        self.verify_hashes_inner(bins_dir, false)
    }

    fn verify_hashes_inner<P: AsRef<Path>>(
        &self,
        bins_dir: P,
        require_metadata: bool,
    ) -> Result<()> {
        let Some(ref stored_hashes) = self.hashes else {
            if require_metadata {
                return Err(anyhow!(
                    "config is missing integrity hashes; refusing to load artifacts without metadata"
                ));
            }
            return Ok(());
        };

        let dir = bins_dir.as_ref();
        let current_hashes = BinaryHashes::from_directory(dir)?;

        let mut mismatches = Vec::new();

        for (filename, get, _set) in ARTIFACTS {
            let stored = get(stored_hashes);
            let current = get(&current_hashes);
            let file_exists = dir.join(filename).is_file();

            match (stored, current) {
                (Some(s), Some(c)) if s != c => {
                    mismatches.push(format!(
                        "{}: expected {}..., got {}...",
                        filename,
                        &s[..s.len().min(16)],
                        &c[..c.len().min(16)]
                    ));
                }
                (Some(_), None) => {
                    mismatches.push(format!(
                        "{}: hash in config but file not found or unreadable",
                        filename
                    ));
                }
                (None, Some(_)) if require_metadata || file_exists => {
                    mismatches.push(format!(
                        "{}: file exists but config is missing its hash",
                        filename
                    ));
                }
                _ => {}
            }
        }

        if mismatches.is_empty() {
            Ok(())
        } else {
            Err(anyhow!(
                "Binary hash verification failed:\n  {}\n\n\
                 This can happen if artifacts were regenerated without updating config.json.\n\
                 Run the circuit builder to regenerate all artifacts and config.",
                mismatches.join("\n  ")
            ))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{BinaryHashes, CircuitBinsConfig};
    use std::{
        fs,
        path::PathBuf,
        time::{SystemTime, UNIX_EPOCH},
    };

    fn temp_dir(name: &str) -> PathBuf {
        let suffix = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("qp-wormhole-config-{name}-{suffix}"));
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn verify_hashes_fails_closed_without_metadata() {
        let dir = temp_dir("missing-metadata");
        fs::write(dir.join("common.bin"), b"common").unwrap();
        let config = CircuitBinsConfig {
            num_leaf_proofs: 2,
            num_layer0_proofs: None,
            hashes: None,
        };

        let err = config.verify_hashes(&dir).unwrap_err();
        assert!(err.to_string().contains("missing integrity hashes"));
        assert!(config.verify_hashes_allow_missing_metadata(&dir).is_ok());

        fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn verify_hashes_rejects_tampered_artifacts() {
        let dir = temp_dir("tampered");
        fs::write(dir.join("common.bin"), b"original").unwrap();

        let config = CircuitBinsConfig {
            num_leaf_proofs: 2,
            num_layer0_proofs: None,
            hashes: Some(BinaryHashes::from_directory(&dir).unwrap()),
        };

        fs::write(dir.join("common.bin"), b"tampered").unwrap();

        let err = config.verify_hashes(&dir).unwrap_err();
        assert!(err.to_string().contains("Binary hash verification failed"));

        fs::remove_dir_all(dir).unwrap();
    }
}
