[package]
name = "wormhole-aggregator"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
plonky2 = { workspace = true }
wormhole-prover = { path = "../prover", default-features = false }
wormhole-verifier = { path = "../verifier", default-features = false }
circuit-common = { path = "../circuit-common" }

[dev-dependencies]
criterion = { workspace = true }

[features]
default = ["std"]
std = [
  "anyhow/std",
  "plonky2/std",
  "wormhole-prover/std",
  "wormhole-verifier/std",
  "circuit-common/std",
]
no_std = []
no_zk = []

[lints]
workspace = true

[[bench]]
name = "aggregator"
harness = false
