name: Rust Basics Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  basics:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        steps:
          - name: Format code
            run: cargo fmt --check

          - name: Clippy lints
            run: cargo clippy --workspace --all-features --all-targets -- -D warnings

          - name: Build project
            run: cargo build --release

          - name: Run tests
            run: cargo test --release --all-features

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: "clippy, rustfmt"

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: ${{ matrix.steps.name }}
      run: ${{ matrix.steps.run }}

