name: Rust Basics Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    name: Format code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: Run rustfmt
        run: cargo fmt --check

  clippy:
    name: Clippy lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

  generate-dummy-proof:
    name: Generate Dummy Proof
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build project
        run: cargo build --release
      - name: Generate dummy proof
        run: cargo run -p wormhole-aggregator --bin generate_dummy_proofs
      - name: Upload dummy proof
        uses: actions/upload-artifact@v4
        with:
          name: dummy-proof
          path: wormhole/aggregator/data/dummy_proof_zk.bin


  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [format, clippy, generate-dummy-proof]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - name: Download dummy proof
        uses: actions/download-artifact@v4
        with:
          name: dummy-proof
          path: wormhole/aggregator/data
      - name: Run tests
        run: cargo test --release --all-features
