name: Create Workspace Release Proposal

env:
  CARGO_TERM_COLOR: always

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch for the PR (default: main)'
        required: false
        type: string
        default: 'main'
      version_type:
        description: 'Type of version bump (major, minor, patch) or specify custom version'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
          - custom
      custom_version:
        description: 'Custom version string (e.g., v0.1.2). Only used if version_type is "custom". MUST start with "v"'
        required: false
      is_draft:
        description: 'Is this a draft release?'
        required: true
        type: boolean
        default: false

jobs:
  calculate-next-version:
    name: 🧮 Calculate Next Workspace Version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.versioner.outputs.new_version }}
      commit_sha_short: ${{ steps.vars.outputs.commit_sha_short }}
      source_branch: ${{ steps.vars.outputs.source_branch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get current branch and commit SHA
        id: vars
        run: |
          echo "commit_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "source_branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT

      - name: Get latest workspace tag
        id: latest_tag
        run: |
          # Get all workspace version tags and sort them by version
          latest_semver_tag=$(git tag -l "zk-circuits-v[0-9]*.[0-9]*.[0-9]*" | sort -V | tail -n 1)

          # If no tags found, use default
          if [ -z "$latest_semver_tag" ]; then
            latest_semver_tag="zk-circuits-v0.0.0"
          fi

          echo "latest_tag_found=$latest_semver_tag" >> $GITHUB_OUTPUT
          echo "Latest workspace semantic version tag found: $latest_semver_tag"

      - name: Calculate new version
        id: versioner
        env:
          LATEST_TAG: ${{ steps.latest_tag.outputs.latest_tag_found }}
          VERSION_TYPE: ${{ github.event.inputs.version_type }}
          CUSTOM_VERSION: ${{ github.event.inputs.custom_version }}
        run: |
          # Remove 'zk-circuits-v' prefix for processing
          current_version=${LATEST_TAG#zk-circuits-v}

          if [[ "$VERSION_TYPE" == "custom" ]]; then
            if [[ -z "$CUSTOM_VERSION" ]]; then
              echo "Error: Custom version is selected but no custom_version string provided."
              exit 1
            fi
            if [[ ! "$CUSTOM_VERSION" =~ ^v ]]; then
              echo "Error: Custom version string MUST start with 'v' (e.g., v1.2.3)."
              exit 1
            fi
            new_version="zk-circuits-$CUSTOM_VERSION"
          else
            # Split version into parts
            IFS='.' read -r major minor patch <<< "$current_version"

            # Increment based on type
            if [[ "$VERSION_TYPE" == "major" ]]; then
              major=$((major + 1))
              minor=0
              patch=0
            elif [[ "$VERSION_TYPE" == "minor" ]]; then
              minor=$((minor + 1))
              patch=0
            elif [[ "$VERSION_TYPE" == "patch" ]]; then
              patch=$((patch + 1))
            else
              echo "Error: Invalid version_type: $VERSION_TYPE"
              exit 1
            fi
            new_version="zk-circuits-v$major.$minor.$patch"
          fi

          echo "New workspace version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

  update-workspace-version:
    name: 📝 Update Workspace Version
    needs: calculate-next-version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create version bump branch and PR
        env:
          NEW_VERSION: ${{ needs.calculate-next-version.outputs.new_version }}
          GITHUB_TOKEN: ${{ secrets.ADMIN_PAT }}
          SOURCE_BRANCH: ${{ needs.calculate-next-version.outputs.source_branch }}
          TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
        run: |
          set -ex
          # Extract numeric version without prefix
          new_cargo_version=${NEW_VERSION#zk-circuits-v}
          branch_name="release/${NEW_VERSION}"

          # Create new branch from source branch
          git checkout "$SOURCE_BRANCH"
          git checkout -b "$branch_name"

          # Update workspace package version in root Cargo.toml
          echo "Updating [workspace.package] version in Cargo.toml to: $new_cargo_version"
          # Portable regex: avoid capturing groups and \s; use POSIX classes
          sed -i -E 's/^version[[:space:]]*=[[:space:]]*"[^"]*"/version = "'$new_cargo_version'"/' Cargo.toml

          echo "Installing cargo-edit for version management"
          cargo install cargo-edit --locked

          echo "Setting workspace version to $new_cargo_version"
          cargo set-version $new_cargo_version --workspace

          echo "Updating version fields in internal dependencies"
          # Update version field in existing dependencies that have both version and path
          # Use sed to update version = "old" to version = "new" in dependency lines
          find . -name "Cargo.toml" -exec sed -i -E "s/(version = \")[0-9]+\\.[0-9]+\\.[0-9]+(\", path = )/\\1$new_cargo_version\\2/g" {} \;

          # Update lockfile for workspace packages only
          cargo update -w
          
          # Verify workspace compiles after version changes
          cargo check --workspace

          # Install formatters
          rustup component add rustfmt --toolchain nightly
          cargo install taplo-cli --locked

          # Format TOML and Rust code to satisfy CI checks
          taplo format --config taplo.toml
          cargo +nightly fmt --all

          # Commit changes
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add Cargo.toml \
            wormhole/circuit/Cargo.toml \
            wormhole/prover/Cargo.toml \
            wormhole/verifier/Cargo.toml \
            wormhole/aggregator/Cargo.toml \
            wormhole/circuit-builder/Cargo.toml \
            wormhole/example/Cargo.toml \
            wormhole/tests/Cargo.toml \
            wormhole/tests/test-helpers/Cargo.toml \
            voting/Cargo.toml \
            Cargo.lock || true
          git commit -m "ci: Automate workspace version bump to $NEW_VERSION"
          git push origin "$branch_name"

          PR_TITLE="ci: Automate workspace version bump to $NEW_VERSION"

          # Prepare labels
          PR_LABELS="automated,release-proposal"
          if [[ "${{ github.event.inputs.is_draft }}" == "true" ]]; then
            PR_LABELS="$PR_LABELS,draft-release"
          fi

          gh pr create \
            --title "$PR_TITLE" \
            --body "$(printf "Automated workspace version bump for release %s.\n\n%s\n\nTriggered by workflow run: %s\n\nType: %s" "$NEW_VERSION" "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" "${{ github.event.inputs.version_type }}")" \
            --base "$TARGET_BRANCH" \
            --head "$branch_name" \
            --label "$PR_LABELS"


